import mongoose from 'mongoose'
import { connectDatabase } from './config/db.js'
import AcademicPlan from './models/academicPlan.model.js'
import Department from './models/department.model.js'
import Course from './models/course.model.js'
import CourseSection from './models/courseSection.model.js'
import User from './models/user.model.js'
import Notification from './models/notification.model.js'
import AcademicRule from './models/academicRule.model.js'
import AcademicWarning from './models/academicWarning.model.js'
import Schedule from './models/schedule.model.js'
import AIRecomendation from './models/AIRecomendation.model.js'

export const seed = async () => {
  await connectDatabase()

  const AcademicPlanModel = AcademicPlan as any
  const DepartmentModel = Department as any
  const CourseModel = Course as any
  const CourseSectionModel = CourseSection as any
  const UserModel = User as any
  const NotificationModel = Notification as any
  const AcademicRuleModel = AcademicRule as any
  const AcademicWarningModel = AcademicWarning as any
  const ScheduleModel = Schedule as any
  const AIRecomendationModel = AIRecomendation as any

  await Promise.all([
    ScheduleModel.deleteMany({}),
    AcademicWarningModel.deleteMany({}),
    NotificationModel.deleteMany({}),
    AIRecomendationModel.deleteMany({}),
    CourseSectionModel.deleteMany({}),
    CourseModel.deleteMany({}),
    DepartmentModel.deleteMany({}),
    UserModel.deleteMany({}),
    AcademicPlanModel.deleteMany({}),
    AcademicRuleModel.deleteMany({}),
  ])

  // ─── Department ────────────────────────────────────────────────────────────
  const department = await DepartmentModel.create({
    department_name: 'Computer Science',
    dean_name: 'Dr. Nizar Sabbah',
  })

  // ─── Courses (from plan PDF – خطة علم الحاسوب 2022) ────────────────────────
  const courseData = [
    // Year 1 – Semester 1
    {
      courseNo: 8239,
      coursesArabicName: 'المهارات الحياتية',
      coursesCreditHours: 2,
      courseLevel: 1,
      courseOrder: 1,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [],
    },
    {
      courseNo: 4001,
      coursesArabicName: 'لغة عربية',
      coursesCreditHours: 3,
      courseLevel: 1,
      courseOrder: 2,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [],
    },
    {
      courseNo: 4004,
      coursesArabicName: 'تفاضل وتكامل 1',
      coursesCreditHours: 3,
      courseLevel: 1,
      courseOrder: 3,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [],
    },
    {
      courseNo: 8996,
      coursesArabicName: 'إنجليزي A2',
      coursesCreditHours: 0,
      courseLevel: 1,
      courseOrder: 4,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [],
    },
    {
      courseNo: 8997,
      coursesArabicName: 'إنجليزي B1',
      coursesCreditHours: 3,
      courseLevel: 1,
      courseOrder: 5,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [8996],
    },
    {
      courseNo: 5055,
      coursesArabicName: 'الحاسوب واساسيات البرمجة',
      coursesCreditHours: 3,
      courseLevel: 1,
      courseOrder: 6,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [],
    },
    {
      courseNo: 5387,
      coursesArabicName: 'كيمياء عامة 1',
      coursesCreditHours: 3,
      courseLevel: 1,
      courseOrder: 7,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [],
    },
    {
      courseNo: 5389,
      coursesArabicName: 'مختبر كيمياء عامة 1',
      coursesCreditHours: 1,
      courseLevel: 1,
      courseOrder: 8,
      courseSemester: 1,
      courseYear: 1,
      preCourse: [5387],
    },
    // Year 1 – Semester 2
    {
      courseNo: 5684,
      coursesArabicName: 'مختبر تطبيقات أنظمة التشغيل',
      coursesCreditHours: 1,
      courseLevel: 2,
      courseOrder: 1,
      courseSemester: 2,
      courseYear: 1,
      preCourse: [5055],
    },
    {
      courseNo: 4076,
      coursesArabicName: 'الرياضيات المتقطعة',
      coursesCreditHours: 3,
      courseLevel: 2,
      courseOrder: 2,
      courseSemester: 2,
      courseYear: 1,
      preCourse: [4004],
    },
    {
      courseNo: 4005,
      coursesArabicName: 'تفاضل وتكامل 2',
      coursesCreditHours: 3,
      courseLevel: 2,
      courseOrder: 3,
      courseSemester: 2,
      courseYear: 1,
      preCourse: [4004],
    },
    {
      courseNo: 8998,
      coursesArabicName: 'إنجليزي B2',
      coursesCreditHours: 3,
      courseLevel: 2,
      courseOrder: 4,
      courseSemester: 2,
      courseYear: 1,
      preCourse: [8997],
    },
    {
      courseNo: 5059,
      coursesArabicName: 'برمجة الحاسوب',
      coursesCreditHours: 3,
      courseLevel: 2,
      courseOrder: 5,
      courseSemester: 2,
      courseYear: 1,
      preCourse: [5055],
    },
    {
      courseNo: 4320,
      coursesArabicName: 'تاريخ فلسطين الحديث',
      coursesCreditHours: 3,
      courseLevel: 2,
      courseOrder: 6,
      courseSemester: 2,
      courseYear: 1,
      preCourse: [],
    },
    {
      courseNo: 8990,
      coursesArabicName: 'مختبر الحاسوب واساسيات البرمجة',
      coursesCreditHours: 1,
      courseLevel: 2,
      courseOrder: 7,
      courseSemester: 2,
      courseYear: 1,
      preCourse: [5055],
    },
    // Year 2 – Semester 3
    {
      courseNo: 5678,
      coursesArabicName: 'المنطق الرقمي',
      coursesCreditHours: 3,
      courseLevel: 3,
      courseOrder: 1,
      courseSemester: 1,
      courseYear: 2,
      preCourse: [4076],
    },
    {
      courseNo: 5050,
      coursesArabicName: 'تركيب البيانات',
      coursesCreditHours: 3,
      courseLevel: 3,
      courseOrder: 2,
      courseSemester: 1,
      courseYear: 2,
      preCourse: [5059],
    },
    {
      courseNo: 5643,
      coursesArabicName: 'أخلاقيات الحاسوب وأمن المعلومات',
      coursesCreditHours: 3,
      courseLevel: 3,
      courseOrder: 3,
      courseSemester: 1,
      courseYear: 2,
      preCourse: [5055],
    },
    {
      courseNo: 4169,
      coursesArabicName: 'جبر خطي 1',
      coursesCreditHours: 3,
      courseLevel: 3,
      courseOrder: 4,
      courseSemester: 1,
      courseYear: 2,
      preCourse: [4004],
    },
    {
      courseNo: 4002,
      coursesArabicName: 'ثقافة اسلامية',
      coursesCreditHours: 3,
      courseLevel: 3,
      courseOrder: 5,
      courseSemester: 1,
      courseYear: 2,
      preCourse: [],
    },
    {
      courseNo: 4308,
      coursesArabicName: 'لغة عبرية',
      coursesCreditHours: 3,
      courseLevel: 3,
      courseOrder: 6,
      courseSemester: 1,
      courseYear: 2,
      preCourse: [],
    },
    // Year 2 – Semester 4
    {
      courseNo: 5193,
      coursesArabicName: 'تحليل عددي',
      coursesCreditHours: 3,
      courseLevel: 4,
      courseOrder: 1,
      courseSemester: 2,
      courseYear: 2,
      preCourse: [4169, 5059],
    },
    {
      courseNo: 8200,
      coursesArabicName: 'الاستخدام الفعال للغة الانجليزية',
      coursesCreditHours: 3,
      courseLevel: 4,
      courseOrder: 2,
      courseSemester: 2,
      courseYear: 2,
      preCourse: [8998],
    },
    {
      courseNo: 5704,
      coursesArabicName: 'تنظيم وعمارة الحاسوب',
      coursesCreditHours: 3,
      courseLevel: 4,
      courseOrder: 3,
      courseSemester: 2,
      courseYear: 2,
      preCourse: [5678],
    },
    {
      courseNo: 5307,
      coursesArabicName: 'برمجة الكيانات',
      coursesCreditHours: 3,
      courseLevel: 4,
      courseOrder: 4,
      courseSemester: 2,
      courseYear: 2,
      preCourse: [5050],
    },
    {
      courseNo: 5270,
      coursesArabicName: 'تصميم وتحليل الخوارزميات',
      coursesCreditHours: 3,
      courseLevel: 4,
      courseOrder: 5,
      courseSemester: 2,
      courseYear: 2,
      preCourse: [5050],
    },
    {
      courseNo: 8999,
      coursesArabicName: 'الريادة',
      coursesCreditHours: 2,
      courseLevel: 4,
      courseOrder: 6,
      courseSemester: 2,
      courseYear: 2,
      preCourse: [],
    },
    // Year 3 – Semester 5
    {
      courseNo: 5999,
      coursesArabicName: 'ادارة واقتصاد',
      coursesCreditHours: 3,
      courseLevel: 5,
      courseOrder: 1,
      courseSemester: 1,
      courseYear: 3,
      preCourse: [],
    },
    {
      courseNo: 5705,
      coursesArabicName: 'نظم التشغيل',
      coursesCreditHours: 3,
      courseLevel: 5,
      courseOrder: 2,
      courseSemester: 1,
      courseYear: 3,
      preCourse: [5704],
    },
    {
      courseNo: 5310,
      coursesArabicName: 'لغات البرمجة',
      coursesCreditHours: 3,
      courseLevel: 5,
      courseOrder: 3,
      courseSemester: 1,
      courseYear: 3,
      preCourse: [5307],
    },
    {
      courseNo: 5268,
      coursesArabicName: 'نظم قواعد البيانات',
      coursesCreditHours: 3,
      courseLevel: 5,
      courseOrder: 4,
      courseSemester: 1,
      courseYear: 3,
      preCourse: [5050],
    },
    {
      courseNo: 4071,
      coursesArabicName: 'الاحتمالات والاحصاء',
      coursesCreditHours: 3,
      courseLevel: 5,
      courseOrder: 5,
      courseSemester: 1,
      courseYear: 3,
      preCourse: [4005],
    },
    {
      courseNo: 5033,
      coursesArabicName: 'تفاعل الإنسان والحاسوب',
      coursesCreditHours: 3,
      courseLevel: 5,
      courseOrder: 6,
      courseSemester: 1,
      courseYear: 3,
      preCourse: [],
    },
    // Year 3 – Semester 6
    {
      courseNo: 5286,
      coursesArabicName: 'برمجة الانترنت',
      coursesCreditHours: 3,
      courseLevel: 6,
      courseOrder: 1,
      courseSemester: 2,
      courseYear: 3,
      preCourse: [5268, 5307],
    },
    {
      courseNo: 4015,
      coursesArabicName: 'أساليب البحث العلمي',
      coursesCreditHours: 2,
      courseLevel: 6,
      courseOrder: 2,
      courseSemester: 2,
      courseYear: 3,
      preCourse: [8998],
    },
    {
      courseNo: 5283,
      coursesArabicName: 'برمجة قواعد البيانات',
      coursesCreditHours: 3,
      courseLevel: 6,
      courseOrder: 3,
      courseSemester: 2,
      courseYear: 3,
      preCourse: [5268],
    },
    {
      courseNo: 5272,
      coursesArabicName: 'مبادئ الذكاء الاصطناعي',
      coursesCreditHours: 3,
      courseLevel: 6,
      courseOrder: 4,
      courseSemester: 2,
      courseYear: 3,
      preCourse: [5270],
    },
    {
      courseNo: 8300,
      coursesArabicName: 'تدريب عملي 1',
      coursesCreditHours: 1,
      courseLevel: 6,
      courseOrder: 5,
      courseSemester: 2,
      courseYear: 3,
      preCourse: [],
    },
    {
      courseNo: 4323,
      coursesArabicName: 'لغة فرنسية',
      coursesCreditHours: 3,
      courseLevel: 6,
      courseOrder: 6,
      courseSemester: 2,
      courseYear: 3,
      preCourse: [],
    },
    // Year 3 – Summer
    {
      courseNo: 4973,
      coursesArabicName: 'التدريب الميداني 1',
      coursesCreditHours: 0,
      courseLevel: 6,
      courseOrder: 7,
      courseSemester: null,
      courseYear: 3,
      preCourse: [],
    },
    // Year 4 – Semester 7
    {
      courseNo: 5706,
      coursesArabicName: 'شبكات الحاسوب',
      coursesCreditHours: 3,
      courseLevel: 7,
      courseOrder: 1,
      courseSemester: 1,
      courseYear: 4,
      preCourse: [5705],
    },
    {
      courseNo: 5273,
      coursesArabicName: 'هندسة البرمجيات',
      coursesCreditHours: 3,
      courseLevel: 7,
      courseOrder: 2,
      courseSemester: 1,
      courseYear: 4,
      preCourse: [5268],
    },
    {
      courseNo: 5311,
      coursesArabicName: 'نظرية الحوسبة',
      coursesCreditHours: 3,
      courseLevel: 7,
      courseOrder: 3,
      courseSemester: 1,
      courseYear: 4,
      preCourse: [5310],
    },
    {
      courseNo: 5703,
      coursesArabicName: 'مقدمة مشروع التخرج',
      coursesCreditHours: 1,
      courseLevel: 7,
      courseOrder: 4,
      courseSemester: 1,
      courseYear: 4,
      preCourse: [5273],
    },
    {
      courseNo: 8442,
      coursesArabicName: 'مختبر هندسة البرمجيات',
      coursesCreditHours: 1,
      courseLevel: 7,
      courseOrder: 5,
      courseSemester: 1,
      courseYear: 4,
      preCourse: [5703],
    },
    // Year 4 – Semester 8
    {
      courseNo: 8301,
      coursesArabicName: 'تدريب عملي 2',
      coursesCreditHours: 1,
      courseLevel: 8,
      courseOrder: 1,
      courseSemester: 2,
      courseYear: 4,
      preCourse: [8300],
    },
    {
      courseNo: 5312,
      coursesArabicName: 'مبادئ المترجمات',
      coursesCreditHours: 3,
      courseLevel: 8,
      courseOrder: 2,
      courseSemester: 2,
      courseYear: 4,
      preCourse: [5311],
    },
    {
      courseNo: 5679,
      coursesArabicName: 'مشروع تخرج',
      coursesCreditHours: 3,
      courseLevel: 8,
      courseOrder: 3,
      courseSemester: 2,
      courseYear: 4,
      preCourse: [5703],
    },
    {
      courseNo: 9000,
      coursesArabicName: 'مساق حر',
      coursesCreditHours: 3,
      courseLevel: 8,
      courseOrder: 4,
      courseSemester: 2,
      courseYear: 4,
      preCourse: [],
    },
  ]
  const courses = await CourseModel.create(
    courseData.map((c: any) => ({ ...c, department_id: department._id })),
  )

  // Helper: find course by courseNo
  const findCourse = (no: number) => courses.find((c: any) => c.courseNo === no)

  // Grade lookup for student 221141
  const gradeMap: Record<number, string> = {
    4002: '98',
    4004: '100',
    4005: '98',
    4071: '100',
    4076: '82',
    4169: '87',
    4308: '99',
    4320: '99',
    4323: '98',
    4973: 'P',
    5033: '99',
    5050: '92',
    5055: '96',
    5059: '99',
    5193: '93',
    5268: '90',
    5270: '93',
    5272: '94',
    5283: '99',
    5286: '93',
    5307: '94',
    5310: '91',
    5387: '97',
    5389: '95',
    5643: '97',
    5678: '98',
    5684: '100',
    5704: '99',
    5705: '97',
    5706: '96',
    5999: '100',
    8200: '97',
    8239: 'P',
    8442: '100',
    8990: '100',
    8996: 'P',
    8997: '96',
    8998: '97',
    8999: '98',
  }

  const planCourse = (no: number, order: number) => ({
    courseNo: no,
    coursesArabicName:
      courseData.find((c) => c.courseNo === no)?.coursesArabicName ?? '',
    coursesCreditHours:
      courseData.find((c) => c.courseNo === no)?.coursesCreditHours ?? 0,
    courseLevel: courseData.find((c) => c.courseNo === no)?.courseLevel ?? 1,
    courseOrder: order,
    courseSemester:
      courseData.find((c) => c.courseNo === no)?.courseSemester ?? null,
    courseYear: courseData.find((c) => c.courseNo === no)?.courseYear ?? null,
    preCourse: courseData.find((c) => c.courseNo === no)?.preCourse ?? [],
    courseGrades: gradeMap[no] ? [gradeMap[no]] : [],
  })

  // ─── Academic Plan (خطة علم الحاسوب 2022 – 129 ساعة) ───────────────────────
  const plan = await AcademicPlanModel.create({
    majorNo: 23103,
    planYear: 2022,
    majorArabicName: 'علم الحاسوب',
    groups: [
      {
        groupArabicName: 'متطلبات الجامعة الإلزامية',
        groupEnglishName: 'University Compulsory Requirements',
        groupNo: 1,
        calcMajorAvg: 0,
        requiredHours: 25,
        passedHours: 22,
        medicineCourses: 0,
        planYear: 2022,
        majorNo: 23103,
        groupCoursList: [
          planCourse(8239, 1),
          planCourse(4001, 2),
          planCourse(4002, 3),
          planCourse(4004, 4),
          planCourse(4005, 5),
          planCourse(4076, 6),
          planCourse(4169, 7),
          planCourse(4320, 8),
          planCourse(8999, 9),
        ],
      },
      {
        groupArabicName: 'متطلبات اللغة والمهارات',
        groupEnglishName: 'Language and Skills Requirements',
        groupNo: 2,
        calcMajorAvg: 0,
        requiredHours: 9,
        passedHours: 9,
        medicineCourses: 0,
        planYear: 2022,
        majorNo: 23103,
        groupCoursList: [
          planCourse(8996, 1),
          planCourse(8997, 2),
          planCourse(8998, 3),
          planCourse(8200, 4),
        ],
      },
      {
        groupArabicName: 'متطلبات التخصص الإلزامية',
        groupEnglishName: 'Major Compulsory Requirements',
        groupNo: 3,
        calcMajorAvg: 1,
        requiredHours: 72,
        passedHours: 63,
        medicineCourses: 0,
        planYear: 2022,
        majorNo: 23103,
        groupCoursList: [
          planCourse(5055, 1),
          planCourse(5684, 2),
          planCourse(8990, 3),
          planCourse(5059, 4),
          planCourse(5678, 5),
          planCourse(5050, 6),
          planCourse(5643, 7),
          planCourse(5704, 8),
          planCourse(5307, 9),
          planCourse(5270, 10),
          planCourse(5193, 11),
          planCourse(4071, 12),
          planCourse(5999, 13),
          planCourse(5705, 14),
          planCourse(5310, 15),
          planCourse(5268, 16),
          planCourse(5286, 17),
          planCourse(5283, 18),
          planCourse(5272, 19),
          planCourse(4015, 20),
          planCourse(5706, 21),
          planCourse(5273, 22),
          planCourse(5311, 23),
          planCourse(5703, 24),
          planCourse(8442, 25),
          planCourse(5312, 26),
          planCourse(5679, 27),
          planCourse(8300, 28),
          planCourse(8301, 29),
        ],
      },
      {
        groupArabicName: 'متطلبات التخصص الاختيارية والحرة',
        groupEnglishName: 'Major Elective and Free Requirements',
        groupNo: 4,
        calcMajorAvg: 0,
        requiredHours: 12,
        passedHours: 10,
        medicineCourses: 0,
        planYear: 2022,
        majorNo: 23103,
        groupCoursList: [
          planCourse(5387, 1),
          planCourse(5389, 2),
          planCourse(4308, 3),
          planCourse(4323, 4),
          planCourse(5033, 5),
          planCourse(4973, 6),
          planCourse(9000, 7),
        ],
      },
    ],
  })

  // ─── Course Sections (2025 / Semester 1) ─────────────────────────────────
  await CourseSectionModel.create([
    {
      acdYear: 2025,
      semesterNo: 1,
      courseNo: 5273,
      courseName: 'هندسة البرمجيات',
      courseCredietHrs: 3,
      sectionNo: 1,
      labSectionNo: -1,
      roomName: 'A-201',
      buildingName: 'مبنى الحاسوب',
      supervisorName: 'محمد جواد عطا الجعبري',
      capacity: 35,
      counter: 28,
      majorNo: 23103,
      isOpen: true,
      packageCaption: 'A',
      secTime: '08:00_08:50 (الاحد, الثلاثاء, الخميس)',
      collageArabicName: 'تكنولوجيا المعلومات وهندسة الحاسوب',
      majorArabicName: 'علم الحاسوب',
      lSectionNo: '',
    },
    {
      acdYear: 2025,
      semesterNo: 1,
      courseNo: 5311,
      courseName: 'نظرية الحوسبة',
      courseCredietHrs: 3,
      sectionNo: 1,
      labSectionNo: -1,
      roomName: 'B-105',
      buildingName: 'مبنى الحاسوب',
      supervisorName: 'Dr. Samer Arandi',
      capacity: 35,
      counter: 30,
      majorNo: 23103,
      isOpen: true,
      packageCaption: 'A',
      secTime: '10:00_10:50 (الاحد, الثلاثاء, الخميس)',
      collageArabicName: 'تكنولوجيا المعلومات وهندسة الحاسوب',
      majorArabicName: 'علم الحاسوب',
      lSectionNo: '',
    },
    {
      acdYear: 2025,
      semesterNo: 1,
      courseNo: 5703,
      courseName: 'مقدمة مشروع التخرج',
      courseCredietHrs: 1,
      sectionNo: 1,
      labSectionNo: -1,
      roomName: 'A-201',
      buildingName: 'مبنى الحاسوب',
      supervisorName: 'محمد جواد عطا الجعبري',
      capacity: 35,
      counter: 28,
      majorNo: 23103,
      isOpen: true,
      packageCaption: 'A',
      secTime: '12:00_12:50 (الاثنين)',
      collageArabicName: 'تكنولوجيا المعلومات وهندسة الحاسوب',
      majorArabicName: 'علم الحاسوب',
      lSectionNo: '',
    },
    {
      // From Postman collection – real section record
      acdYear: 2025,
      semesterNo: 1,
      courseNo: 4001,
      courseName: 'لغة عربية',
      courseCredietHrs: 3,
      sectionNo: 9,
      labSectionNo: -1,
      roomName: '003 (مدرج بلال عمرو)',
      buildingName: 'وادي الهرية C',
      supervisorName: 'جهاد علي محمد العدرة',
      capacity: 40,
      counter: 0,
      majorNo: 23101,
      isOpen: true,
      packageCaption: 'A',
      secTime: '15:00_15:50 (الاحد, الثلاثاء, الخميس)',
      collageArabicName: 'تكنولوجيا المعلومات وهندسة الحاسوب',
      majorArabicName: 'هندسة أنظمة الحاسوب A',
      lSectionNo: '',
    },
  ])

  // ─── Users ─────────────────────────────────────────────────────────────────
  const supervisor = await UserModel.create({
    name: 'Mohammad Jawad Al-Jabari',
    email: 'jabary980@ppu.edu',
    password: 'pass1234',
    role: 'supervisor',
  })

  await UserModel.create({
    name: 'Admin User',
    email: 'admin@coursemate.dev',
    password: 'pass1234',
    role: 'admin',
  })

  // Student – Hasan Mohammad Al-Saafin (student no. 221141)
  const student = await UserModel.create({
    name: 'Hasan Mohammad Al-Saafin',
    email: 'hasan@gmail.com',
    password: 'pass1234',
    role: 'student',
    student_data: {
      studentNo: 221141,
      gpa: 95.8,
      academic_plan: plan._id,
      supervisor: {
        supervisorNo: 444,
        supervisorArabicName: 'محمد جواد عطا الجعبري',
        supervisorEmail: 'jabary980@ppu.edu',
      },
      notifications: [],
      // All 39 completed courses from grades API (grades/studentinsemester)
      completed_courses: [
        {
          courseNo: 4002,
          courseArabicName: 'ثقافة اسلامية',
          academicYear: 2022,
          semesterNo: 1,
          creditHours: '3',
          grade: '98',
        },
        {
          courseNo: 4004,
          courseArabicName: 'تفاضل وتكامل 1',
          academicYear: 2022,
          semesterNo: 1,
          creditHours: '3',
          grade: '100',
        },
        {
          courseNo: 4005,
          courseArabicName: 'تفاضل وتكامل 2',
          academicYear: 2022,
          semesterNo: 2,
          creditHours: '3',
          grade: '98',
        },
        {
          courseNo: 4071,
          courseArabicName: 'الاحتمالات والاحصاء',
          academicYear: 2024,
          semesterNo: 1,
          creditHours: '3',
          grade: '100',
        },
        {
          courseNo: 4076,
          courseArabicName: 'الرياضيات المتقطعة',
          academicYear: 2022,
          semesterNo: 2,
          creditHours: '3',
          grade: '82',
        },
        {
          courseNo: 4169,
          courseArabicName: 'جبر خطي 1',
          academicYear: 2023,
          semesterNo: 1,
          creditHours: '3',
          grade: '87',
        },
        {
          courseNo: 4308,
          courseArabicName: 'لغة عبرية',
          academicYear: 2023,
          semesterNo: 1,
          creditHours: '3',
          grade: '99',
        },
        {
          courseNo: 4320,
          courseArabicName: 'تاريخ فلسطين الحديث',
          academicYear: 2022,
          semesterNo: 2,
          creditHours: '3',
          grade: '99',
        },
        {
          courseNo: 4323,
          courseArabicName: 'لغة فرنسية',
          academicYear: 2024,
          semesterNo: 2,
          creditHours: '3',
          grade: '98',
        },
        {
          courseNo: 4973,
          courseArabicName: 'التدريب الميداني 1',
          academicYear: 2024,
          semesterNo: 3,
          creditHours: '0',
          grade: 'P',
        },
        {
          courseNo: 5033,
          courseArabicName: 'تفاعل الإنسان والحاسوب',
          academicYear: 2024,
          semesterNo: 1,
          creditHours: '3',
          grade: '99',
        },
        {
          courseNo: 5050,
          courseArabicName: 'تركيب البيانات',
          academicYear: 2023,
          semesterNo: 1,
          creditHours: '3',
          grade: '92',
        },
        {
          courseNo: 5055,
          courseArabicName: 'الحاسوب واساسيات البرمجة',
          academicYear: 2022,
          semesterNo: 1,
          creditHours: '3',
          grade: '96',
        },
        {
          courseNo: 5059,
          courseArabicName: 'برمجة الحاسوب',
          academicYear: 2022,
          semesterNo: 2,
          creditHours: '3',
          grade: '99',
        },
        {
          courseNo: 5193,
          courseArabicName: 'تحليل عددي',
          academicYear: 2023,
          semesterNo: 2,
          creditHours: '3',
          grade: '93',
        },
        {
          courseNo: 5268,
          courseArabicName: 'نظم قواعد البيانات',
          academicYear: 2024,
          semesterNo: 1,
          creditHours: '3',
          grade: '90',
        },
        {
          courseNo: 5270,
          courseArabicName: 'تصميم وتحليل الخوارزميات',
          academicYear: 2023,
          semesterNo: 2,
          creditHours: '3',
          grade: '93',
        },
        {
          courseNo: 5272,
          courseArabicName: 'مبادئ الذكاء الاصطناعي',
          academicYear: 2024,
          semesterNo: 2,
          creditHours: '3',
          grade: '94',
        },
        {
          courseNo: 5283,
          courseArabicName: 'برمجة قواعد البيانات',
          academicYear: 2024,
          semesterNo: 2,
          creditHours: '3',
          grade: '99',
        },
        {
          courseNo: 5286,
          courseArabicName: 'برمجة الانترنت',
          academicYear: 2024,
          semesterNo: 2,
          creditHours: '3',
          grade: '93',
        },
        {
          courseNo: 5307,
          courseArabicName: 'برمجة الكيانات',
          academicYear: 2023,
          semesterNo: 2,
          creditHours: '3',
          grade: '94',
        },
        {
          courseNo: 5310,
          courseArabicName: 'لغات البرمجة',
          academicYear: 2024,
          semesterNo: 1,
          creditHours: '3',
          grade: '91',
        },
        {
          courseNo: 5387,
          courseArabicName: 'كيمياء عامة 1',
          academicYear: 2022,
          semesterNo: 1,
          creditHours: '3',
          grade: '97',
        },
        {
          courseNo: 5389,
          courseArabicName: 'مختبر كيمياء عامة 1',
          academicYear: 2022,
          semesterNo: 1,
          creditHours: '1',
          grade: '95',
        },
        {
          courseNo: 5643,
          courseArabicName: 'أخلاقيات الحاسوب وأمن المعلومات',
          academicYear: 2023,
          semesterNo: 1,
          creditHours: '3',
          grade: '97',
        },
        {
          courseNo: 5678,
          courseArabicName: 'المنطق الرقمي',
          academicYear: 2023,
          semesterNo: 1,
          creditHours: '3',
          grade: '98',
        },
        {
          courseNo: 5684,
          courseArabicName: 'مختبر تطبيقات أنظمة التشغيل',
          academicYear: 2022,
          semesterNo: 2,
          creditHours: '1',
          grade: '100',
        },
        {
          courseNo: 5704,
          courseArabicName: 'تنظيم وعمارة الحاسوب',
          academicYear: 2023,
          semesterNo: 2,
          creditHours: '3',
          grade: '99',
        },
        {
          courseNo: 5705,
          courseArabicName: 'نظم التشغيل',
          academicYear: 2024,
          semesterNo: 1,
          creditHours: '3',
          grade: '97',
        },
        {
          courseNo: 5706,
          courseArabicName: 'شبكات الحاسوب',
          academicYear: 2024,
          semesterNo: 2,
          creditHours: '3',
          grade: '96',
        },
        {
          courseNo: 5999,
          courseArabicName: 'ادارة واقتصاد',
          academicYear: 2024,
          semesterNo: 1,
          creditHours: '3',
          grade: '100',
        },
        {
          courseNo: 8200,
          courseArabicName: 'الاستخدام الفعال للغة الانجليزية',
          academicYear: 2023,
          semesterNo: 2,
          creditHours: '3',
          grade: '97',
        },
        {
          courseNo: 8239,
          courseArabicName: 'المهارات الحياتية',
          academicYear: 2022,
          semesterNo: 1,
          creditHours: '2',
          grade: 'P',
        },
        {
          courseNo: 8442,
          courseArabicName: 'مختبر هندسة البرمجيات',
          academicYear: 2024,
          semesterNo: 2,
          creditHours: '1',
          grade: '100',
        },
        {
          courseNo: 8990,
          courseArabicName: 'مختبر الحاسوب واساسيات البرمجة',
          academicYear: 2022,
          semesterNo: 2,
          creditHours: '1',
          grade: '100',
        },
        {
          courseNo: 8996,
          courseArabicName: 'إنجليزي A2',
          academicYear: 2022,
          semesterNo: 1,
          creditHours: '0',
          grade: 'P',
        },
        {
          courseNo: 8997,
          courseArabicName: 'إنجليزي B1',
          academicYear: 2022,
          semesterNo: 2,
          creditHours: '3',
          grade: '96',
        },
        {
          courseNo: 8998,
          courseArabicName: 'إنجليزي B2',
          academicYear: 2023,
          semesterNo: 1,
          creditHours: '3',
          grade: '97',
        },
        {
          courseNo: 8999,
          courseArabicName: 'الريادة',
          academicYear: 2023,
          semesterNo: 2,
          creditHours: '2',
          grade: '98',
        },
      ],
    },
  })

  // ─── Notification ───────────────────────────────────────────────────────────
  const notification = await NotificationModel.create({
    userId: student._id,
    type: 'academic',
    message: 'تم تسجيلك في مساق هندسة البرمجيات للفصل الأول 2025.',
    isRead: false,
  })

  await UserModel.updateOne(
    { _id: student._id },
    { $push: { 'student_data.notifications': notification._id } },
  )

  // ─── Academic Rule ──────────────────────────────────────────────────────────
  await AcademicRuleModel.create({
    rule_type: 'min_gpa',
    description: 'Students with GPA below 60 receive an academic warning.',
  })

  // ─── Academic Warnings (from registrationinfo/academicInfo) ────────────────
  await AcademicWarningModel.create([
    {
      user_id: student._id,
      caption: 'آخر فصل دراسي مفروز:',
      value: 'الصيفي 2024/2025',
      textColour: 'primary',
      orderNo: 1,
    },
    {
      user_id: student._id,
      caption: 'الوضع الاكاديمي:',
      value: 'منتظم',
      textColour: 'primary',
      orderNo: 2,
    },
    {
      user_id: student._id,
      caption: 'التحذيرات الأكاديمية:',
      value: '0',
      textColour: 'primary',
      orderNo: 4,
    },
    {
      user_id: student._id,
      caption: 'معدل الفصل الأخير:',
      value: '96.3',
      textColour: 'primary',
      orderNo: 5,
    },
    {
      user_id: student._id,
      caption: 'المعدل التخصصي:',
      value: '95.5',
      textColour: 'primary',
      orderNo: 6,
    },
    {
      user_id: student._id,
      caption: 'المعدل التراكمي:',
      value: '95.8',
      textColour: 'primary',
      orderNo: 7,
    },
    {
      user_id: student._id,
      caption: 'الساعات المسجلة:',
      value: '101',
      textColour: 'primary',
      orderNo: 8,
    },
    {
      user_id: student._id,
      caption: 'الساعات المقطوعة بنجاح:',
      value: '101',
      textColour: 'primary',
      orderNo: 9,
    },
    {
      user_id: student._id,
      caption: 'المستوى بالفصول:',
      value: '6',
      textColour: 'primary',
      orderNo: 10,
    },
    {
      user_id: student._id,
      caption: 'التخصص:',
      value: 'علم الحاسوب',
      textColour: 'primary',
      orderNo: 11,
    },
    {
      user_id: student._id,
      caption: 'الدرجة العلمية:',
      value: 'البكالوريوس',
      textColour: 'primary',
      orderNo: 3,
    },
    {
      user_id: student._id,
      caption: 'سنة قانون التسجيل:',
      value: '2023',
      textColour: 'primary',
      orderNo: 14,
    },
    {
      user_id: student._id,
      caption: 'سنة خطة التخرج:',
      value: '2022',
      textColour: 'primary',
      orderNo: 15,
    },
    {
      user_id: student._id,
      caption: 'الإنتظام:',
      value: 'منتظم',
      textColour: 'primary',
      orderNo: 21,
    },
    {
      user_id: student._id,
      caption: 'تخصص التوجيهي:',
      value: 'علمي',
      textColour: 'primary',
      orderNo: 17,
    },
    {
      user_id: student._id,
      caption: 'معدل التوجيهي:',
      value: '92.6',
      textColour: 'primary',
      orderNo: 18,
    },
    {
      user_id: student._id,
      caption: 'مجموعة الطالب:',
      value: 'A',
      textColour: 'primary',
      orderNo: 20,
    },
    {
      user_id: student._id,
      caption: 'المشرف الأكاديمي:',
      value: 'محمد جواد عطا الجعبري  jabary980@ppu.edu',
      textColour: 'primary',
      orderNo: 22,
    },
  ])

  // ─── Semester History (from registrationinfo/semesters) ────────────────────
  await ScheduleModel.create([
    {
      student_id: student._id,
      studentNo: 221141,
      academicYear: 2022,
      academicYearTitle: '2022/2023',
      semesterNo: 1,
      semesterTitle: 'الأول',
      semesterHours: 15,
      passHours: 15,
      semesterAverage: 97.5,
      majorAverage: 0,
      accumulativeAverage: 97.5,
      academicWarning: '0',
      academicStatus: 'منتظم',
    },
    {
      student_id: student._id,
      studentNo: 221141,
      academicYear: 2022,
      academicYearTitle: '2022/2023',
      semesterNo: 2,
      semesterTitle: 'الثاني',
      semesterHours: 17,
      passHours: 17,
      semesterAverage: 95.4,
      majorAverage: 0,
      accumulativeAverage: 96.3,
      academicWarning: '0',
      academicStatus: 'منتظم',
    },
    {
      student_id: student._id,
      studentNo: 221141,
      academicYear: 2023,
      academicYearTitle: '2023/2024',
      semesterNo: 1,
      semesterTitle: 'الأول',
      semesterHours: 18,
      passHours: 18,
      semesterAverage: 95.0,
      majorAverage: 0,
      accumulativeAverage: 95.8,
      academicWarning: '0',
      academicStatus: 'منتظم',
    },
    {
      student_id: student._id,
      studentNo: 221141,
      academicYear: 2023,
      academicYearTitle: '2023/2024',
      semesterNo: 2,
      semesterTitle: 'الثاني',
      semesterHours: 17,
      passHours: 17,
      semesterAverage: 95.5,
      majorAverage: 99,
      accumulativeAverage: 95.8,
      academicWarning: '0',
      academicStatus: 'منتظم',
    },
    {
      student_id: student._id,
      studentNo: 221141,
      academicYear: 2024,
      academicYearTitle: '2024/2025',
      semesterNo: 1,
      semesterTitle: 'الأول',
      semesterHours: 18,
      passHours: 18,
      semesterAverage: 96.2,
      majorAverage: 95.2,
      accumulativeAverage: 95.8,
      academicWarning: '0',
      academicStatus: 'منتظم',
    },
    {
      student_id: student._id,
      studentNo: 221141,
      academicYear: 2024,
      academicYearTitle: '2024/2025',
      semesterNo: 2,
      semesterTitle: 'الثاني',
      semesterHours: 16,
      passHours: 16,
      semesterAverage: 96.3,
      majorAverage: 95.5,
      accumulativeAverage: 95.8,
      academicWarning: '0',
      academicStatus: 'منتظم',
    },
    {
      student_id: student._id,
      studentNo: 221141,
      academicYear: 2024,
      academicYearTitle: '2024/2025',
      semesterNo: 3,
      semesterTitle: 'الصيفي',
      semesterHours: 0,
      passHours: 0,
      semesterAverage: 0,
      majorAverage: 95.5,
      accumulativeAverage: 95.8,
      academicWarning: '0',
      academicStatus: 'منتظم',
    },
  ])

  // ─── AI Recommendation ─────────────────────────────────────────────────────
  const nextCourses = [5273, 5311, 5703]
    .map((no) => findCourse(no)?._id)
    .filter(Boolean)
  await AIRecomendationModel.create({
    student_id: student._id,
    supervisor_id: supervisor._id,
    courses: nextCourses,
    reason:
      'Based on completed semesters 1–6 and a 95.8 accumulative average, the student is ready for year-4 courses: Software Engineering, Theory of Computation, and Graduation Project Introduction.',
    confidenceScore: 0.95,
  })

  console.log('Database seeded successfully')
}

seed()
  .then(() => {
    console.log('Seeding completed')
  })
  .catch((error) => {
    console.error('Seeding failed:', error)
    process.exitCode = 1
  })
  .finally(async () => {
    await mongoose.connection.close()
  })
